version: '3.8'
services:
  stats-client:
    build: ./statistic/stat_client
    container_name: stat-client
    ports:
      - "9090:9090"
    depends_on: [ stats-server ]
    environment:
      - STATS_SERVER_URL=http://stats-server:9091

  stats-server:
    build: ./statistic/stat_server
    container_name: stat-server
    ports:
      - "9091:9091"
    depends_on: [ stats-db ]
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    depends_on: [ ewm-db ]
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STATS_CLIENT_URL=http://stats-client:9090

  ewm-db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root