version: '3.8'
services:
  stats-client:
    build: ./statistic/stat_client
    container_name: stat_client
    ports:
      - "9090:9090"
    depends_on: [ stats-server ]
    environment:
      - STATS_SERVER_URL=http://localhost:9091

  stats-server:
    build: ./statistic/stat_server
    container_name: stat_server
    ports:
      - "9091:9091"
    depends_on: [ stats-db ]
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stats_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:13.7-alpine
