server:
  port: 9091

# Mode to apply when determining whether initialization should be performed.
spring:
  sql:
    init:
      mode: always
  datasource:
    # Fully qualified name of the JDBC driver
    driver-class-name: org.postgresql.Driver
    # JDBC URL of the database.
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    # Login username of the database.
    username: ${POSTGRES_USER}
    # Login password of the database.
    password: ${POSTGRES_PASSWORD}
  jpa:
    # Whether to enable logging of SQL statements.
    show-sql: true
    hibernate:
      # DDL mode
      ddl-auto: none
    properties:
      hibernate:
        # SQL Dialects.
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        # Pretty print the SQL.
        format_sql: true